name: Build Docker Images

on:
  push:
    branches:
      - main
      - dev
      - demo
  pull_request:
    branches:
      - main
      - dev
      - demo
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize
  merge_group:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: rag-adminwebapp
            dockerfile: docker/Admin.Dockerfile
          - app_name: rag-backend
            dockerfile: docker/Backend.Dockerfile
          - app_name: rag-webapp
            dockerfile: docker/Frontend.Dockerfile
    uses: ./.github/workflows/build-docker.yml
    with:
      # Use a multi-line format for conditional registry assignment
      registry: |
        ${{ github.ref_name == 'main' && 'pslpricwydregistry.azurecr.io,cwydcontainerregpk.azurecr.io' || 'cwydcontainerregpk.azurecr.io' }}

      # Define username dynamically based on the branch using multi-line syntax
      username: |
        ${{ github.ref_name == 'main' && 'pslpricwydregistry' || 'cwydcontainerregpk' }}
      
      # Pass the app name and dockerfile paths based on the matrix configuration
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      
      # Set push condition for all branches
      push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' }}
      
    secrets: inherit
